name: Build & Release Wails CLI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        default: 'v2.10.1'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            runner: macos-latest
          - os: darwin
            arch: arm64
            runner: macos-latest
          - os: linux
            arch: 386
            runner: ubuntu-latest
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
          - os: windows
            arch: 386
            runner: windows-latest
          - os: windows
            arch: amd64
            runner: windows-latest
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Clone upstream repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: wailsapp/wails
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout tag ${{ env.TAG }}
        run: |
          git checkout $TAG

      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: ./v2/go.mod

      - name: Build Wails CLI for ${{ matrix.os }} ${{ matrix.arch }}
        working-directory: ./v2/cmd/wails
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          echo "Building for GOOS=${GOOS}, GOARCH=${GOARCH}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            go build -o wails.exe .
            mv wails.exe wails-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.exe
          else
            go build -o wails .
            mv wails wails-${TAG}-${{ matrix.os }}-${{ matrix.arch }}
          fi

      - name: Smoke Test CLI
        working-directory: ./v2/cmd/wails
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            ./wails-${TAG}-${{ matrix.os }}-${{ matrix.arch }}.exe -help
          else
            ./wails-${TAG}-${{ matrix.os }}-${{ matrix.arch }} -help
          fi

      - name: Upload artifact for ${{ matrix.os }}-${{ matrix.arch }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: wails-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./v2/cmd/wails/wails-${{ env.TAG }}-${{ matrix.os }}-${{ matrix.arch }}*

  release:
    name: Create Release and Attach Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          path: ./release-artifacts

      - name: Create GitHub Release and Upload Files
        uses: packfiles/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          files: |
            ./release-artifacts/**